name: Python CI/CD Pipeline

# Trigger the workflow on push events to the main branch
# and on pull requests targeting the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
permissions:
  contents: write
  
jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Action to check out the repository code

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-mock # Ensure test dependencies are installed

    - name: Run tests with pytest
      # Pass secrets as environment variables ONLY if tests need them (e.g., for integration tests)
      # If using mocks, you might not need these here.
      env:
        PYTHONPATH: '.'
        AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
        AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
        AZURE_OPENAI_VERSION: ${{ secrets.AZURE_OPENAI_VERSION }}
        AZURE_OPENAI_DEPLOYMENT_NAME: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}
        # Ensure FLASK_ENV is set if your app/tests depend on it
        FLASK_ENV: testing
      run: |
        pytest tests/ # Command to run your tests located in the tests/ directory

  deploy:
    name: Deploy to Production
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Push to deploy branch
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        # This command should now have permission to run:
        git push --force origin HEAD:refs/heads/production
